title: Introduction To Genomic Analysis
description: "A workshop series for Canadian researchers utilizing Compute Canada resources"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
   - jekyll-coffeescript
   - jekyll-paginate
